// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCz5DtPlvRnlIGbRtEMJIytzX92AkDGs',
    appId: '1:789094140356:web:231f1be950624184323c91',
    messagingSenderId: '789094140356',
    projectId: 'ithutechmessage',
    authDomain: 'ithutechmessage.firebaseapp.com',
    storageBucket: 'ithutechmessage.firebasestorage.app',
    measurementId: 'G-1Y1XK7SZBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9sjk9K4puGle2nI_Ekx8-UANdp18zBS8',
    appId: '1:789094140356:android:3ebbcb69ece67971323c91',
    messagingSenderId: '789094140356',
    projectId: 'ithutechmessage',
    storageBucket: 'ithutechmessage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI0S_68qDNykpI_e6nb3YMMubRCAAVAY4',
    appId: '1:789094140356:ios:f203cdaac3cb23e0323c91',
    messagingSenderId: '789094140356',
    projectId: 'ithutechmessage',
    storageBucket: 'ithutechmessage.firebasestorage.app',
    iosBundleId: 'com.example.itmessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI0S_68qDNykpI_e6nb3YMMubRCAAVAY4',
    appId: '1:789094140356:ios:f203cdaac3cb23e0323c91',
    messagingSenderId: '789094140356',
    projectId: 'ithutechmessage',
    storageBucket: 'ithutechmessage.firebasestorage.app',
    iosBundleId: 'com.example.itmessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCz5DtPlvRnlIGbRtEMJIytzX92AkDGs',
    appId: '1:789094140356:web:e5f92bfce160e653323c91',
    messagingSenderId: '789094140356',
    projectId: 'ithutechmessage',
    authDomain: 'ithutechmessage.firebaseapp.com',
    storageBucket: 'ithutechmessage.firebasestorage.app',
    measurementId: 'G-EVDQNC1KKB',
  );

}